In [5]:
from tensorflow.keras.preprocessing.text import one_hot
import numpy as np

sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

1. We should fix a vocaubulary size that will help us in representation.

2. Based on vocabulary size, we can one hote encode the words of the sentences.

In [18]:
voc_size = 100
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[13, 71, 71, 14], [13, 71, 71, 5], [13, 56, 71, 7], [3, 30, 3, 86, 14], [3, 30, 3, 86, 26], [97, 13, 50, 71, 77], [24, 14, 45, 86]]


1. For implementation of embedding matrix in keras layers we need to have a size of the embedding layer also known as dimension.

2. What actually is embedding layer doing?<br>
It is feature representation, lets say i have a word BOY, and my embedding dimension is 10. So the vector representing the word boy will have the size equals to 10. So if a sentence is having 8 number of words, and emdedding dimension is said to be 10.
The embedding matrix for that sentence will be equal to (8,10).
For each word in the sentence from 0....7 ,I will have a vector of dimemnsion 10.
3. Another thing that we need to take care about is padding, so all sentences are not of same length, so what we can do is we can have a fixed sentence length that will pad the sentences when they are smaller from the desired size.

In [19]:
 from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential


sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[ 0  0  0  0 13 71 71 14]
 [ 0  0  0  0 13 71 71  5]
 [ 0  0  0  0 13 56 71  7]
 [ 0  0  0  3 30  3 86 14]
 [ 0  0  0  3 30  3 86 26]
 [ 0  0  0 97 13 50 71 77]
 [ 0  0  0  0 24 14 45 86]]


In [20]:
# Dimension for each feature 

dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [15]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [24]:
print(model.predict(embedded_docs)[0])

[[ 0.03496313  0.04286364  0.02410268 -0.02876645  0.01484202 -0.01748316
  -0.04163278 -0.04111578 -0.00385138  0.045369  ]
 [ 0.03496313  0.04286364  0.02410268 -0.02876645  0.01484202 -0.01748316
  -0.04163278 -0.04111578 -0.00385138  0.045369  ]
 [ 0.03496313  0.04286364  0.02410268 -0.02876645  0.01484202 -0.01748316
  -0.04163278 -0.04111578 -0.00385138  0.045369  ]
 [ 0.03496313  0.04286364  0.02410268 -0.02876645  0.01484202 -0.01748316
  -0.04163278 -0.04111578 -0.00385138  0.045369  ]
 [-0.01617346 -0.00043703  0.02660931  0.04483845 -0.018908   -0.01193035
  -0.0393031   0.00770854  0.01298909  0.03455018]
 [ 0.00967842  0.02840439 -0.03080238  0.02907977  0.00583106  0.01440724
   0.03723377 -0.04170398 -0.028197   -0.02958464]
 [ 0.00967842  0.02840439 -0.03080238  0.02907977  0.00583106  0.01440724
   0.03723377 -0.04170398 -0.028197   -0.02958464]
 [-0.02699585  0.01594957  0.01017511 -0.04188485  0.02635803 -0.02835122
   0.01018913 -0.03975717 -0.02353048 -0.04458045]]

In [25]:
print(model.predict(embedded_docs)[0].shape)

(8, 10)
